---
- name: redhat | installing epel repo (RedHat)
  yum:
    name: "epel-release"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | installing dependencies
  yum:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'python-devel'
    - 'python-pip'
  when: ansible_distribution != "Fedora"

- name: redhat | installing add'l dependencies (Fedora)
  dnf:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'jq'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == "Fedora"

- name: redhat | installing add'l dependencies (Not Fedora)
  yum:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'jq'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == "Fedora"
