---
- name: haproxy | configuring haproxy
  template:
    src: "etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "reload haproxy"
