---
- name: config_kvm | configuring kvm
  template: src=etc/libvirt/libvirtd.conf.j2 dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=0644
  notify:
    - restart kvm

- name: config_kvm | configuring kvm
  replace: dest=/etc/default/libvirt-bin regexp="^libvirtd_opts=\"-d\"" replace="libvirtd_opts=\"-d -l\""
  notify:
    - restart kvm
  when: enable_kvm_tcp is defined and enable_kvm_tcp

- name: config_kvm | disabling apparmor profiles for libvirt
  file: src={{ item.src }} dest={{ item.dest }} state=link
  register: libvirt_apparmor_disabled
  with_items:
    - src: /etc/apparmor.d/usr.sbin.libvirtd
      dest: /etc/apparmor.d/disable/usr.sbin.libvirtd
    - src: /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
      dest: /etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper

- name: config_kvm | disabling apparmor profiles for libvirt
  command: "apparmor_parser -R {{ item }}"
  with_items:
    - /etc/apparmor.d/usr.sbin.libvirtd
    - /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
  when: libvirt_apparmor_disabled.changed
