---
- name: config_logstash | clearing existing logstash config
  file:
    path: "{{ logstash_config_dir }}"
    state: "absent"
  become: true
  when: >
        clear_logstash_config is defined and
        clear_logstash_config

- name: config_logstash | setup logstash config directory and set permissions
  file:
    path: "{{ logstash_config_dir }}"
    state: "directory"
    owner: "logstash"
    group: "logstash"
    recurse: no
    mode: 0775
  become: true

- name: config_logstash | removing original logstash config if it exists
  file:
    path: "{{ logstash_config_dir }}/logstash.conf"
    state: "absent"
  become: true
  notify: "restart logstash"

- name: config_logstash | configuring logstash
  template:
    src: "etc/logstash/conf.d/{{ item }}.conf.j2"
    dest: "{{ logstash_config_dir }}/{{ item }}.conf"
    owner: "logstash"
    group: "logstash"
    mode: 0644
    #validate: "/opt/logstash/bin/logstash -tf %s" # commented due to error during tests with file not found.
  become: true
  notify: "restart logstash"
  with_items: '{{ logstash_base_configs }}'

- name: config_logstash | creating logstash pattern folders
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "logstash"
    group: "logstash"
    mode: 0775
    recurse: yes
  become: true
  with_items:
    - '/opt/logstash/lib/logstash/outputs/elasticsearch'
    - '/opt/logstash/patterns'

- name: config_logstash | test logstash configuration
  shell: "{{ logstash_bin }} -t -f {{ logstash_config_dir }} --path.settings /etc/logstash/"
  become: true
  changed_when: false
  when: logstash_major_ver == '5.x'
