---
- name: galera_monitoring | configuring monitor script for galera
  template:
    src: "etc/mysql/{{ galera_monitor_script_name }}.j2"
    dest: "{{ galera_monitor_script_path }}/{{ galera_monitor_script_name }}"
    owner: "mysql"
    group: "mysql"
    mode: "u=rwx,g=rwx,o="
  become: true
  register: galera_monitoring_updated

- name: galera_monitoring | restarting mysql on master
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when: >
        inventory_hostname == galera_mysql_master_node and
        galera_monitoring_updated.changed

- name: galera_monitoring | waiting for mysql to start on master
  wait_for:
    port: 3306
  when: inventory_hostname == galera_mysql_master_node

- name: galera_monitoring | restarting mysql on additional servers
  service:
    name: "mysql"
    state: "restarted"
  become: true
  when: >
        inventory_hostname != galera_mysql_master_node and
        galera_monitoring_updated.changed
