---
# tasks file for ansible-mariadb-galera-cluster
- include: unconfigure_cluster.yml
  when: >
        galera_reconfigure_galera is defined and
        galera_reconfigure_galera

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: setup_cluster.yml

- include: mysql_users.yml
  tags: mysql-users
  when: mariadb_mysql_users is defined

- include: galera_monitoring.yml
  tags:
    - config_galera_monitoring
  when: galera_enable_galera_monitoring_script

- include: configure_root_access.yml

- include: cacti.yml
  when: galera_enable_cacti_monitoring
