---
# tasks file for ansible-change-hostname
- name: main | changing hostname to match inventory_hostname_short
  hostname:
    name: "{{ inventory_hostname_short }}"
  register: hostname_status
  when: ansible_hostname != "{{ inventory_hostname_short }}"

- name: main | restarting machine
  shell: sleep 2 && shutdown -r now "rebooting to complete hostname change"
  async: 1
  poll: 0
  ignore_errors: true
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed

- name: main | waiting for server to come back
  local_action: wait_for port=22 host="{{ ansible_ssh_host  | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
  become: false
  when: >
        (change_hostname_reboot is defined and
        change_hostname_reboot ) and
        hostname_status.changed
