---
- name: cron | creating cron script
  template:
    src: "dns_check.sh.j2"
    dest: "/etc/cron.d/dns_check.sh"
    owner: "root"
    group: "root"
    mode: 0774
  become: true

- name: cron | creating cron job
  cron:
    name: "dns check"
    minute: "*/5"
    job: "/etc/cron.d/dns_check.sh"
    state: "present"
  become: true
