galaxy_info:
  author: Larry Smith Jr.
  description: An Ansible role to install/configure Powershell

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - system

dependencies: []
