---
- src: https://github.com/mrlesmithjr/ansible-apt-cacher-ng.git
- src: https://github.com/mrlesmithjr/ansible-change-hostname.git
- src: https://github.com/mrlesmithjr/ansible-dnsmasq.git
- src: https://github.com/mrlesmithjr/ansible-docker.git
- src: https://github.com/mrlesmithjr/ansible-etc-hosts.git
- src: https://github.com/mrlesmithjr/ansible-glusterfs.git
- src: https://github.com/mrlesmithjr/ansible-isc-dhcp.git
- src: https://github.com/mrlesmithjr/ansible-k8s.git
- src: https://github.com/mrlesmithjr/ansible-ntp.git
- src: https://github.com/mrlesmithjr/ansible-sshd.git
- src: https://github.com/mrlesmithjr/ansible-timezone.git
