---
# handlers file for ansible-netdata
#
- name: reload systemd netdata
  systemd:
    name: "netdata"
    daemon_reload: true
  become: true

- name: restart netdata
  service:
    name: "netdata"
    state: "restarted"
    enabled: true
    sleep: 10
  become: true

- name: start netdata
  service:
    name: "netdata"
    state: "started"
    enabled: true
  become: true

- name: stop netdata
  service:
    name: "netdata"
    state: "stopped"
    enabled: true
  become: true
