---
# handlers file for ansible-prometheus-node-exporter
- name: reload systemd
  systemd:
    daemon_reload: true
    name: "node_exporter"
  become: true

- name: restart node_exporter
  service:
    name: "node_exporter"
    state: "restarted"
  become: true
