---
# defaults file for ansible-mdadm
#
# Define Raid Arrays to manage
mdadm_arrays:
    # Define array name
  - name: 'md0'
    # Define disk devices to assign to array
    devices:
      - '/dev/sdb'
      - '/dev/sdc'
    # Define filesystem to partition array with
    filesystem: 'ext4'
    # Define the array raid level
    # 0|1|4|5|6|10
    level: '1'
    # Define mountpoint for array device
    mountpoint: '/mnt/md0'
    # Define if array should be present or absent
    state: 'present'
    # Set mount options (optional)
    opts: 'noatime'
  # - name: 'md0'
  #   devices:
  #     - '/dev/sdb'
  #     - '/dev/sdc'
  #     - '/dev/sdd'
  #   filesystem: 'ext4'
  #   level: '5'
  #   mountpoint: '/mnt/md0'
  #   state: 'present'
