---
# defaults file for ansible-keepalived
keepalived_config: false
keepalived_router_info: []
  # - name: vrrp_1
  #   check_script:
  #     - name: chk_haproxy
  #       script: 'killall -0 haproxy'
  #       interval: 2
  #       weight: 2
  #   # Define inventory_hostname of node to be considered Master
  #   master_node: node0
  #   router_id: 50
  #   router_pri_backup: 100
  #   router_pri_master: 150
  #   vip_int: '{{ ansible_eth1.device }}'
  #   vip_addresses:
  #     - 192.168.202.100
  #     - 192.168.202.101
  # - name: vrrp_2
  #   check_script:
  #     - name: chk_nginx
  #       script: 'pidof nginx'
  #       interval: 2
  #       weight: 2
  #   master_node: node1
  #   router_id: 51
  #   router_pri_backup: 100
  #   router_pri_master: 150
  #   vip_int: '{{ ansible_eth1.device }}'
  #   vip_addresses:
  #     - 192.168.202.102
