galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install [OpenJDK](http://openjdk.java.net/)

  license: license (MIT)

  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
    - name: Ubuntu
      versions:
        - artful
        - precise
        - trusty
        - xenial
        - zesty

  galaxy_tags: []

dependencies: []
