galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure [OpenStack Compute Service Controller](https://docs.openstack.org/ocata/install-guide-ubuntu/nova-controller-install.html)

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - openstack

dependencies: []
