---
# handlers file for ansible-apache2
- name: restart apache2
  service: name=apache2 state=restarted

- name: reload apache2
  service: name=apache2 state=reloaded

- name: "restart httpd"
  service:
    name: "httpd"
    state: "restarted"
