---
- name: debian | Installing mdadm
  apt:
    name: "mdadm"
    state: "present"

- name: arrays | Setting distribution-specific facts
  set_fact:
    update_initramfs: "update-initramfs -u"
    mdadm_conf: "/etc/mdadm/mdadm.conf"
    mdadm_conf_path: "/etc/mdadm"
