---
- src: https://github.com/mrlesmithjr/ansible-chrony
- src: https://github.com/mrlesmithjr/ansible-config-interfaces
- src: https://github.com/mrlesmithjr/ansible-etc-hosts
- src: https://github.com/mrlesmithjr/ansible-memcached
- src: https://github.com/mrlesmithjr/ansible-mysql
- src: https://github.com/mrlesmithjr/ansible-openstack-base
- src: https://github.com/mrlesmithjr/ansible-openstack-identity-service
- src: https://github.com/mrlesmithjr/ansible-openstack-image-service
- src: https://github.com/mrlesmithjr/ansible-openstack-openrc
- src: https://github.com/mrlesmithjr/ansible-rabbitmq
