---
# defaults file for ansible-prometheus-node-exporter
prometheus_node_exporter_download: '{{ prometheus_node_exporter_download_url }}/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz'
prometheus_node_exporter_download_url: 'https://github.com/prometheus/node_exporter/releases/download'
prometheus_node_exporter_install_dir: '/opt'
prometheus_node_exporter_listen_port: '9100'
prometheus_node_exporter_source_dir: '/usr/local/src'
prometheus_node_exporter_version: '0.14.0'

prometheus_node_exporter_user_info:
  group: 'prometheus'
  user: 'prometheus'
