---
- name: redhat | installing packages
  yum:
    name: ["ntp"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_distribution != "Fedora"

- name: redhat | installing packages
  dnf:
    name: ["ntp"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_distribution == "Fedora"

- name: redhat | configuring ntp
  template:
    src: etc/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: restart ntpd

- name: redhat | ensuring ntpd service is started and enabled on boot
  service:
    name: ntpd
    state: started
    enabled: true
  become: true
