---
galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure [GitLab Runner](https://docs.gitlab.com/runner/)

  license: license (MIT)

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie

  galaxy_tags:
    - ci/cd

dependencies: []
