---
- name: users | Creating SSH User {{ stackstorm_ssh_info.user }}
  user:
    name: "{{ stackstorm_ssh_info.user }}"
    generate_ssh_key: yes
    ssh_key_file: "{{ stackstorm_ssh_info.key_file }}"
    state: present
  tags:
    - stackstorm-ssh-keys
    - stackstorm-user
  become: true

- name: users | Configuring Sudoers For User {{ stackstorm_ssh_info.user }}
  template:
    src: etc/sudoers.d/st2.j2
    dest: /etc/sudoers.d/st2
    owner: root
    group: root
    mode: 0440
  tags:
    - stackstorm-user
  become: true

# Download SSH Pub Key for SSH User
# We can then push this key out to remote hosts authorized_keys
- name: users | Downloading {{ stackstorm_ssh_info.user }} SSH Public Key
  fetch:
    src: "{{ stackstorm_ssh_info.key_file }}.pub"
    dest: "./{{ stackstorm_ssh_info.user }}@{{ ansible_hostname }}.pub"
    flat: yes
  tags:
    - stackstorm-ssh-keys
    - stackstorm-user
  become: true
