---
- name:       redhat | installing pre-reqs
  yum:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - MySQL-python
  when:       ansible_distribution != "Fedora"

- name:       redhat | installing mysql CentOS 6
  yum:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - mysql-server
    - mysql
  when:       >
        ansible_distribution != "Fedora" and
        (ansible_distribution_version < '7')

- name:       redhat | Installing Pre-Reqs On Fedora
  dnf:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - libselinux-python
    - mysql-devel
    - python-devel
    - python-dnf
  when:       >
        ansible_distribution == "Fedora"

- name:       redhat | Installing MySQL Fedora
  dnf:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - mysql-server
    - mysql
  when:       >
        ansible_distribution == "Fedora"

- name:       redhat | Installing Python Modules For Fedora
  pip:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - mysql-python
  when:       >
        ansible_distribution == "Fedora"

- name:       redhat | Ensuring mysqld Is Enabled and Starts On Boot
  service:
    name:     mysqld
    state:    started
    enabled:  true
  become:     true
  when:       >
        (ansible_distribution == "CentOS" and
        ansible_distribution_version < "7") or
        (ansible_distribution == "Fedora" and
        (ansible_distribution_version == "24" or
        ansible_distribution_version == "25"))

- name:       redhat | installing mariadb mysql CentOS 7
  yum:
    name:     "{{ item }}"
    state:    present
  become:     true
  with_items:
    - mariadb-server
    - mariadb
  when:       >
        ansible_distribution != "Fedora" and
        (ansible_distribution_version >= '7')

- name:       redhat | configuring mysql
  template:
    src:      etc/my.cnf.j2
    dest:     /etc/my.cnf
    owner:    root
    group:    root
    mode:     0644
  register:   mariadb_reconfigured_redhat
  become:     true
  notify:     restart mariadb
  when:       >
        ansible_distribution != "Fedora" and
        (ansible_distribution_version >= '7')

- name:       redhat | Ensuring mariadb Service Is Enabled and Starts On Boot
  service:
    name:     mariadb
    state:    started
    enabled:  yes
  become:     true
  when:       >
        (ansible_distribution == "CentOS" and
        ansible_distribution_version >= '7') or
        (ansible_distribution == "Fedora" and
        (ansible_distribution_version <= "23" or
        ansible_distribution_version >= "26"))
