---
- name: config_haproxy | checking for haproxy rsyslog config
  stat:
    path: "/etc/rsyslog.d/49-haproxy.conf"
  register: "rsyslog_haproxy_conf"

- name: config_haproxy | configuring haproxy rsyslog config
  template:
    src: "etc/rsyslog.d/49-haproxy.conf.j2"
    dest: "/etc/rsyslog.d/49-haproxy.conf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: "restart rsyslog"
  when: rsyslog_haproxy_conf.stat.exists

- name: config_haproxy | configuring haproxy
  template:
    src: "etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  register: haproxy_reconfigured

- name: config_haproxy | restarting haproxy
  service:
    name: "haproxy"
    state: "restarted"
  become: true
  when: >
        haproxy_reconfigured['changed'] and
        not ansible_check_mode
