---
# tasks file for ansible-consul
- import_tasks: set_facts.yml
  tags:
    - consul_facts

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: accounts.yml

- import_tasks: install.yml

- import_tasks: config.yml

- import_tasks: services.yml

- import_tasks: app_services.yml
  tags:
    - consul-app-services
  when: >
        consul_services is defined and
        consul_services

- import_tasks: acl.yml
  tags:
    - consul-acl
  when: consul_acl is defined and
        consul_acl and
        consul_datacenter == consul_acl_datacenter

- import_tasks: dnsmasq.yml
  when: >
        consul_enable_dnsmasq is defined and
        consul_enable_dnsmasq
