---
# defaults file for ansible-base

base_arch_packages:
  - 'base-devel'
  - 'curl'
  - 'git'
  - 'git-core'
  - 'ntp'
  - 'sg3_utils'

base_debian_packages:
  - 'build-essential'
  - 'software-properties-common'
  - 'curl'
  - 'git'
  - 'git-core'
  - 'ntp'
  - 'scsitools'

# apt-get upgrade
base_debian_upgrade: false

# apt-get dist-upgrade
base_debian_dist_upgrade: false

# Define DNS servers to update to if update_dns_nameservers = true
base_dns_nameservers:
  - '8.8.8.8'
  - '8.8.4.4'

# Defines if /etc/network/interfaces dns-nameservers is present or not
# Only used when update_dns_nameservers=true
base_dns_nameservers_state: 'present'

# Defines dns-search for /etc/network/interfaces
base_dns_search: 'example.org'

# Defines if /etc/network/interfaces dns-search is present or not
# Only used if base_update_dns_search=true
base_dns_search_state: 'present'

# Defines if apt-get udpate should be forced
base_force_apt_update: false

base_redhat_packages:
  - 'curl'
  - 'git'
  - 'nano'
  - 'net-tools'
  - 'ntp'
  - 'sg3_utils'

# Defines if dhcp client config should be updated
base_update_dhcpclient_conf: false

# Defines if dns servers should be updated
base_update_dns_nameservers: false

# Defines if dns search domain should be updated
base_update_dns_search: false
