---
- name: setting Debian facts
  set_fact:
    nginx_web_group: "www-data"
    nginx_web_owner: "www-data"
    nginx_web_root: "/usr/share/nginx/html"
  when: ansible_os_family == "Debian"

- name: setting RedHat facts
  set_fact:
    nginx_web_group: "nginx"
    nginx_web_owner: "nginx"
    nginx_web_root: "/usr/share/nginx/html"
  when: ansible_os_family == "RedHat"

- name: setting PHP version
  set_fact:
    nginx_php_path: 'etc/php5'  #no leading / for template path
    nginx_php_ver: 5
  when: >
        ansible_distribution == "Debian" or
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version <= '14.04')

- name: setting PHP version
  set_fact:
    nginx_php_path: 'etc/php/7.0'  #no leading / for template path
    nginx_php_ver: 7.0
  when: >
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version >= '16.04')
