galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible] role to install/configure [tftpd-hpa]
  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial

  galaxy_tags:
    - system
    - network

dependencies: []
