---
# tasks file for ansible-digital-rebar

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: install.yml

- include_tasks: service.yml

- include_tasks: config.yml
