---
# tasks file for ansible-haproxy
- include: debian.yml
  tags:
    - haproxy
  when: ansible_os_family == "Debian"

- include: redhat.yml
  tags:
    - haproxy
  when: ansible_os_family == "RedHat"

- include: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- include: config_haproxy.yml
  tags:
    - config_haproxy
    - haproxy
  when: config_haproxy is defined and config_haproxy
