---
- src: https://www.github.com/mrlesmithjr/ansible-change-hostname.git
- src: https://www.github.com/mrlesmithjr/ansible-docker.git
- src: https://www.github.com/mrlesmithjr/ansible-etc-hosts.git
- src: https://www.github.com/mrlesmithjr/ansible-k8s.git
- src: https://www.github.com/mrlesmithjr/ansible-ntp.git
- src: https://www.github.com/mrlesmithjr/ansible-timezone.git
