---
# handlers file for ansible-kea-dhcp
- name: "restart redhat kea-dhcp"
  service:
    name: "{{ item.name }}"
    state: "restarted"
  with_items: '{{ kea_dhcp_redhat_services }}'
  when: >
      ansible_os_family == "RedHat" and
      item.enabled

- name: "restart debian kea-dhcp"
  service:
    name: "{{ item.name }}"
    state: "restarted"
  with_items: '{{ kea_dhcp_debian_services }}'
  when: >
      ansible_os_family == "Debian" and
      item.enabled
