galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure an NFS Client

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - system

dependencies: []
