---
- name: redhat | installing unbound
  yum:
    name: "unbound"
    state: present
  when: ansible_os_family != "Fedora"

- name: redhat | installing unbound
  dnf:
    name: "unbound"
    state: present
  when: ansible_os_family == "Fedora"
