galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure [influxdata Kapacitor](https://www.influxdata.com/time-series-platform/kapacitor/)

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - monitoring

dependencies: []
