---
k8s_advertise_address_int: "{{ rpi_wired_int }}"

k8s_cluster_group: rpi_k8s

k8s_cluster_init_skip_ca_verification: true

k8s_dashboard: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard-arm.yaml

k8s_helm_architecture: arm

k8s_helm_install: true

k8s_helm_version: 2.8.1

k8s_pod_network_config: "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
# k8s_pod_network_config: https://gist.githubusercontent.com/mrlesmithjr/eab451b45641db6c108ca3f362563621/raw/93569a17d4085975fc2305ae117ce720766174ec/weave-daemonset-2.2.0.yaml

k8s_users:
  - user: pi

k8s_version: 1.11.2
