---
galaxy_info:
  author: Larry Smith Jr.
  description: Installs Rundeck

  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - vivid
    - wily
    - xenial
  - name: Debian
    versions:
    - jessie
    - wheezy

  categories:
  - development
  - system
dependencies: []
