---
galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible] role to install/configure [NGINX]

  license: MIT
  min_ansible_version: 1.2

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
        - zesty
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy

  galaxy_tags:
    - web

dependencies: []
