---
- name: redhat | installing keepalived
  yum:
    name: "keepalived"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | installing keepalived
  dnf:
    name: "keepalived"
    state: "present"
  become: true
  when: ansible_distribution == "Fedora"

- name: redhat | enabling keepalived on boot and start
  service:
    name: "keepalived"
    state: "started"
    enabled: yes
  become: true
  when: not ansible_check_mode

- name: redhat | allowing VIP to come up on both nodes
  sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: 1
    state: "present"
    reload: yes
  become: true
