---
- name: config_glusterfs_server | reconfiguring /etc/init/mounting-glusterfs.conf to start earlier on boot
  template:
    src: "etc/init/mounting-glusterfs.conf.j2"
    dest: "/etc/init/mounting-glusterfs.conf"
    owner: root
    group: root
    mode: 0644

- name: config_glusterfs_server | connecting gluster peers
  shell: gluster peer probe {{ item }}
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  ignore_errors: true  #added temporarily to get around Vagrant testing...may remove later
  delegate_to: "{{ glusterfs_server_master }}"
  with_items: '{{ groups[glusterfs_server_group] }}'
  when: >
        item != glusterfs_server_master and
        ((groups[glusterfs_arbiter_group] is defined and
        inventory_hostname not in groups[glusterfs_arbiter_group]) or
        groups[glusterfs_arbiter_group] is not defined)

- name: config_glusterfs_server | creating brick folders
  file:
    path: "{{ glusterfs_brick_dir }}/.{{ item.name }}/"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  with_items: '{{ glusterfs_create_bricks }}'
  when: >
        ((groups[glusterfs_arbiter_group] is defined and
        inventory_hostname not in groups[glusterfs_arbiter_group]) or
        groups[glusterfs_arbiter_group] is not defined)

- name: config_glusterfs_server | Capture Gluster Volumes
  command: "gluster volume list"
  register: "gluster_volumes"
  # We do this to ensure this executes in --check mode
  check_mode: no
  changed_when: false

- name: config_glusterfs_server | create gluster volume
  gluster_volume:
    state: present
    name: "{{ item.name }}"
    brick: "{{ glusterfs_brick_dir }}/.{{ item.name }}"
    force: "{{ glusterfs_volume_force_create }}"
    replicas: "{{ groups[glusterfs_server_group]|length }}"
    cluster: "{% for host in groups[glusterfs_server_group] %}{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"
  with_items: '{{ glusterfs_create_bricks }}'
  when: >
        inventory_hostname == glusterfs_server_master and
        item.name not in gluster_volumes.stdout
