---
- include: mysql_root_pw.yml

- name: redhat | adding mariadb repo
  template:
    src: "etc/yum.repos.d/MariaDB.repo.j2"
    dest: "/etc/yum.repos.d/MariaDB.repo"
    owner: "root"
    group: "root"
  become: true
  register: repo_added

- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: "present"
    update_cache: yes
  become: true
  with_items:
    - 'MySQL-python'
    - 'socat'
  when: >
        ansible_distribution != "Fedora"

- name: Precreate /etc/my.cnf.d in case we need to add mariadb_config_overrides file
  file:
    path: /etc/my.cnf.d
    state: directory
    mode: 0755
    recurse: yes
  become: true
  changed_when: false
  when: mariadb_config_overrides is defined

- name: redhat | add an overrides file
  template:
    src: "etc/mariadb_overrides.cnf.j2"
    dest: "/etc/my.cnf.d/overrides.cnf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when: mariadb_config_overrides is defined

- name: redhat | installing mariadb mysql
  yum:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'MariaDB-server'
    - 'galera'
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing mariadb mysql
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - 'MariaDB-server'
    - 'galera'
    - 'MySQL-python'
  when: >
        ansible_distribution == "Fedora"

- name: Remove migrated-from-my.cnf-settings.conf that is causing MariaDB to not start
  file:
    path: /etc/systemd/system/mariadb.service.d/migrated-from-my.cnf-settings.conf
    state: absent
  become: true

- name: reload systemd for MariaDB changes
  become: true
  systemd:
    daemon_reload: true

- name: redhat | ensuring mariadb mysql is enabled on boot and started
  service:
    name: "mysql"
    state: "started"
    enabled: yes
  become: true
