---
- name: config | Configuring NGNIX Load Balancer
  template:
    src: "etc/nginx/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  become: true
  notify: "restart nginx"
