---
- name: debian_pdns_recursor | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'dnsutils'

- name: debian_pdns_recursor | installing powerdns recursor
  apt:
    deb: "{{ pdns_recursor_download_url }}/deb/pdns-recursor_{{ pdns_recursor_version }}_amd64.deb"
    state: "present"
  become: true
  notify: restart pdns recursor
  when: >
        ansible_architecture == "x86_64" and
        pdns_recursor_version != "4.x"

- name: debian_pdns_recursor | installing powerdns recursor
  apt:
    deb: "{{ pdns_recursor_download_url }}/deb/pdns-recursor_{{ pdns_recursor_version }}_i386.deb"
    state: "present"
  become: true
  notify: restart pdns recursor
  when: >
        ansible_architecture == "i386" and
        pdns_recursor_version != "4.x"

- name: Adding PowerDNS Repo Key
  apt_key:
    url: "https://repo.powerdns.com/FD380FBB-pub.asc"
    state: "present"
  become: true
  when: pdns_recursor_version == "4.x"

- name: Pinning PowerDNS Repo
  template:
    src: "pdns_repo.j2"
    dest: "/etc/apt/preferences.d/pdns"
  become: true
  when: pdns_recursor_version == "4.x"

- name: Adding PowerDNS Repo
  apt_repository:
    repo: "deb http://repo.powerdns.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }}-rec-40 main"
    state: "present"
  become: true
  when: >
        ansible_lsb['id'] != "Raspbian" and
        pdns_recursor_version == "4.x"

- name: Adding PowerDNS Repo
  apt_repository:
    repo: "deb http://repo.powerdns.com/raspbian {{ ansible_distribution_release|lower }}-rec-40 main"
    state: "present"
  become: true
  when: >
        ansible_lsb['id'] == "Raspbian" and
        pdns_recursor_version == "4.x"

- name: Installing PowerDNS Recursor
  apt:
    name: "{{ item }}"
    state: "latest"
  become: true
  # We do this in order to allow the service to not fail starting when initially starting on port 53
  ignore_errors: true
  with_items:
    - 'pdns-recursor'
  when: pdns_recursor_version == "4.x"
