---
# defaults file for ansible-drbd
drbd_common:
  disk: ''
  net: |
    cram-hmac-alg sha1;
    shared-secret "{{ drbd_network_shared_secret }}";
  handlers: ''
  startup: ''
  options: ''

drbd_disks:
  - device: /dev/drbd0
    disk: /dev/sdb
    filesystem: ext4
    partitions: 1
    mountpoint: /opt/nfs
    mountopts: defaults
    resource: r0
    state: present
    use_partition: /dev/sdb1

drbd_group: test_nodes

drbd_interface: enp0s8

drbd_network_shared_secret: wXE8MqVa

drbd_vip: 192.168.250.100

# Debian9/Ubuntu have included drbd support.
drbd_deb_packages: ['drbd8-utils']
# Additional yum repo required. See ELREPO for prebuilt RHEL RPMS, or your local site administrator.
drbd_rpm_packages: ['drbd84-utils', 'kmod-drbd84']

# Toggle
drbd_use_heartbeat: true
drbd_use_parted: true
drbd_unicast_mode: false
drbd_unicast_port: 694
