---
- name: dnsmasq | installing dnsmasq (Debian)
  apt:
    name: "dnsmasq"
    state: "present"
  become: true
  when: ansible_os_family == "Debian"

- name: dnsmasq | installing dnsmasq (Fedora)
  dnf:
    name: "dnsmasq"
    state: "present"
  become: true
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora"

- name: dnsmasq | installing dnsmasq (RedHat, but not Fedora)
  yum:
    name: "dnsmasq"
    state: "present"
  become: true
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

- name: dnsmasq | ensuring dnsmasq service is enabled
  service:
    name: "dnsmasq"
    enabled: yes
  become: true

- name: dnsmasq | configuring dnsmasq to resolv consul dns
  template:
    src: "etc/dnsmasq.d/10-consul.j2"
    dest: "/etc/dnsmasq.d/10-consul"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  become: true
  notify:
    - "restart dnsmasq"
