---
# tasks file for ansible-kibana
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config_kibana.yml
  when: kibana['config']

- include_tasks: plugins.yml

- include_tasks: service.yml
